export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        process: "readonly",
        console: "readonly",
        Buffer: "readonly",
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        __filename: "readonly",
        exports: "readonly",
        Promise: "readonly",
        Error: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Array: "readonly",
        Object: "readonly",
        Map: "readonly",
        Set: "readonly",
        Symbol: "readonly",
        BigInt: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "prefer-const": "warn",
      "no-var": "error",
      eqeqeq: ["error", "always"],
      curly: ["warn", "multi-line"],
      "no-undef": "error",
    },
  },
  {
    ignores: ["node_modules/", ".vercel/", ".next/", "eslint.config.mjs"],
  },
];
